title: My 1944ish Willys MB-38
email: your-email@domain.com
description: This is about my Willys MB-38 Jeep. Hopefully I can get it to run.
url: "https://mb38.github.io"
markdown: kramdown
paginate: 3
paginate_path: "/posts/:num"

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
