title: My MB-38 project
tagline: In February 2017 I found, what I believe to be, a 1944 Willys MB-38 Jeep from World War 2. This is how I'm dealing with that decision.
email: your-email@domain.com
description: This is about my Willys MB-38 Jeep. Hopefully I can get it to run and do something with it.
url: "https://mb38.github.io"
markdown: kramdown
paginate: 3
paginate_path: "/posts/:num"

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
